version: '3.9'

volumes:
  postgres_data:

services:
  web:
    build: ./.

    ports:
      - "8080:8080"

    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
